spring:
  application:
    name: FullStack
  datasource:
    url: jdbc:mysql://localhost:3306/fullstack
    username: root
    password: 4433
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


